http-rust1.73/Dockerfile
http-rust1.73/Kraftfile
http-rust1.73/README.md
http-rust1.73/server.rs

Introduce simple Rust1.73 simple HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: Rust filesystem, including toolchain and libraries
* `server.rs`: the simple HTTP server implementation

feat: Introduce simple Rust1.73 HTTP server

---

http-php8.2/Dockerfile
http-php8.2/Kraftfile
http-php8.2/README.md
http-php8.2/http_server.php
http-php8.2/php.ini

Introduce simple PHP8.2 HTTP server to be deployed on KraftCloud.  It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: PHP filesystem, including binaries and libraries
* `server.py`: the HTTP server implementation

feat: Introduce simple PHP8.2 HTTP server

---

http-cpp/Dockerfile
http-cpp/Kraftfile
http-cpp/README.md
http-cpp/http_server.cpp

Introduce simple C++ HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: filesystem, including binary and libraries
* `http_server.cpp`: the simple HTTP server implementation

feat: Introduce simple C++ HTTP server

---

http-cpp-boost/Dockerfile
http-cpp-boost/Kraftfile
http-cpp-boost/README.md
http-cpp-boost/http_server.cpp

Introduce simple C++ Boost HTTP server (i.e. using `libboost`) to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: filesystem, including binary and libraries
* `http_server.cpp`: the simple HTTP server implementation

feat: Introduce simple C++ Boost HTTP server

---

http-lua5.1/Dockerfile
http-lua5.1/Kraftfile
http-lua5.1/README.md
http-lua5.1/http_server.lua

Introduce Lua5.1 HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Kraftfile`: build / run rules, including pulling the `lua:5.1` image
* `Dockerfile`: the application filesystem, comprised solely of the `http_server.lua` script
* `http_server.lua`: the HTTP server implementation

feat: Introduce Lua5.1 HTTP server

---

http-rust1.75-tokio/Cargo.toml
http-rust1.75-tokio/Dockerfile
http-rust1.75-tokio/Kraftfile
http-rust1.75-tokio/README.md
http-rust1.75-tokio/src/main.rs

Introduce Rust Tokio server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` official image).
Add:
* `Kraftfile`: build / run rules, including pulling the `base:latest` official image
* `Dockerfile`: the application filesystem, comprised of Rust Tokio files and application binary executable
* `Cargo.toml`: Rust Cargo dependency files
* `src/`: the application directory

feat(examples): Introduce Rust Tokio

---

http-ruby3.2/Dockerfile
http-ruby3.2/Kraftfile
http-ruby3.2/README.md
http-ruby3.2/server.rb

Introduce simple Ruby3.2 HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: Ruby filesystem, including binaries and libraries
* `server.py`: the HTTP server implementation

feat: Introduce simple Ruby3.2 HTTP server

---

http-perl5.38/Dockerfile
http-perl5.38/Kraftfile
http-perl5.38/README.md
http-perl5.38/server.pl

Introduce simple Perl5.38 HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: Perl filesystem, including binaries and libraries
* `server.py`: the HTTP server implementation

feat: Introduce simple Perl5.38 HTTP server

---

http-python3.12/Dockerfile
http-python3.12/Kraftfile
http-python3.12/README.md
http-python3.12/server.py

Introduce simple Python3.12 HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: Python filesystem, including binaries and libraries
* `server.py`: the simple HTTP server implementation

feat: Introduce simple Python3.12 HTTP server

---

http-node21/Dockerfile
http-node21/Kraftfile
http-node21/README.md
http-node21/server.js

Introduce simple Node21 HTTP server to be deployed on KraftCloud. It uses binary compatibility mode (i.e. the `base` image).
Add:
* `Dockerfile`: Node filesystem, including binaries and libraries
* `server.py`: the HTTP server implementation

feat: Introduce simple Node21 HTTP server

---

node21-expressjs/.dockerignore
node21-expressjs/.gitignore
node21-expressjs/Dockerfile
node21-expressjs/Kraftfile
node21-expressjs/README.md
node21-expressjs/app/index.js
node21-expressjs/package.json

Introduce ExpressJS (Node framework) to be deployed on KraftCloud. It uses binary compatibility mode. It uses the `node:21` runtime.
Add:
* `Kraftfile`: build / run rules, including pulling the `node` image
* `Dockerfile`: ExpressJS filesystem
* `package.json`: install dependencies
* `app/index.js`: the actual ExpressJS implementation

feat(examples): Introduce ExpressJS on Node

---

imaginary/Kraftfile
imaginary/README.md

Introduce Imaginary example to be deployed on KraftCloud. It uses binary compatibility mode. It uses the `imaginary:1.2` runtime.
Add:
* `Kraftfile`: build / run rules, including pulling the `imaginary:1.2` image

feat(examples): Introduce Imaginary example

---

java17-springboot3.2.x/DemoApplication.java
java17-springboot3.2.x/Dockerfile
java17-springboot3.2.x/Kraftfile
java17-springboot3.2.x/README.md

Introduce Spring Boot example based on the `java:17` runtime.
Add Dockerfile to configure and fetch project template from [https://start.spring.io](https://start.spring.io). Replace `DemoApplication.java` with "Hello World" example from [https://spring.io/quickstart](https://spring.io/quickstart).

feat(examples): Introduce Spring Boot example

---

ruby3.2-rails/.dockerignore
ruby3.2-rails/Dockerfile
ruby3.2-rails/Kraftfile
ruby3.2-rails/README.md
ruby3.2-rails/app/controllers/hello_controller.rb
ruby3.2-rails/app/views/hello/index.html.erb
ruby3.2-rails/config/environments/development.rb
ruby3.2-rails/config/routes.rb

Introduce Rails (Ruby framework) to be deployed on KraftCloud. It uses binary compatibility mode. It uses the `ruby:3.2` runtime.
Add:
* `Kraftfile`: build / run rules, including pulling the `ruby` image
* `Dockerfile`: Rails filesystem
* `app/`, `config/`: the actual Rails implementation

feat(examples): Introduce Ruby Rails example

---

ferretdb/.dockerignore
ferretdb/.gitignore
ferretdb/Dockerfile
ferretdb/Kraftfile
ferretdb/README.md

Introduce FerretDB to be deployed on KraftCloud. It uses binary-compatibility mode. It uses the `ferretdb:1.2` runtime.
Add:
* `Kraftfile`: build / run rules, including pulling the `ferretdb` image
* `Dockerfile`: placeholder to build / extend filesystem

feat(examples): Introduce FerretDB

---

bun/.dockerignore
bun/.gitignore
bun/Dockerfile
bun/Kraftfile
bun/README.md
bun/server.ts

Introduce a Bun example to be deployed on KraftCloud. It uses the `base-compat` image.
Add:
* `Dockerfile`: placeholder to extract the filesystem
* `server.ts`: simple Bun server implementation
* `.dockerignore` / `.gitignore`: ignore generated files

feat(examples): Add Bun example

---

http-elixir1.16/.dockerignore
http-elixir1.16/.formatter.exs
http-elixir1.16/.gitignore
http-elixir1.16/Dockerfile
http-elixir1.16/Kraftfile
http-elixir1.16/README.md
http-elixir1.16/lib/server.ex
http-elixir1.16/lib/server/application.ex
http-elixir1.16/mix.exs
http-elixir1.16/test/server_test.exs
http-elixir1.16/test/test_helper.exs
http-elixir1.16/wrapper.sh

Introduce HTTP server written in Elixir. It uses the base-compat (Tinyx) image.
Add:
* `Dockerfile`: placeholder to extract the filesystem
* `lib/`, `mix.exs`, `.formatter.exs`, `test/`: Elixir files
* `wrapper.sh`: wrapper script to start the server
* `.dockerignore` / `.gitignore`: ignore generated files

feat(examples): Add HTTP server in Elixir

---

puppeteer/.dockerignore
puppeteer/.gitignore
puppeteer/.puppeteerrc.cjs
puppeteer/Dockerfile
puppeteer/Dockerfile.full
puppeteer/Kraftfile
puppeteer/README.md
puppeteer/pdf.js
puppeteer/wrapper.sh

Introduce a Puppeteer example to be deployed on KraftCloud. It uses the `base-compat:latest` image.
Add:
* `Dockerfile`: placeholder to extract the filesystem
* `pdf.js`: implementation of a PDF converter
* `.dockerignore` / `.gitignore`: ignore generated files

feat(examples): Add Puppeteer example

---

tyk/README.md
tyk/compose.yaml

Tyk requires Redis support so two connected instances must be created on KraftCloud: Tyk and Redis. Use Compose support for that, as defined in `compose.yaml`.

feat(examples): Use Compose for Tyk

---

llama2/Kraftfile
minio/Kraftfile
spin-wagi-http/Kraftfile
tyk/Kraftfile

For application that have issues, disable scale-to-zero via the `labels` attribute in `Kraftfile`.

fix(examples): Fix labels for non-working applications

---

ferretdb/README.md
mariadb/README.md
memcached/README.md
mongodb/README.md
postgres/README.md
redis/README.md
wordpress/README.md

Use `<NAME>.<METRO>.kraft.host` instead of `<NAME>.<METRO>.kraft.cloud` throughout `README.md` files.

fix(examples): Use kraft.host in README files

---

http-elixir1.16/Kraftfile

Elixir goes through a number of actions to start the network service. It requires more that `1000ms` for proper stateful start. Increase cooldown to `3000ms`.
Note that after starting an Elixir instance, several seconds are required for it to reach the final state. During that time, requests will fail. After that, queries will work as expected, in a stateful setup.

http-elixir: Fix stateful cooldown

---

imaginary/Kraftfile

Add scale-to-zero labels in the `Kraftfile` for imaginary.

feat(imaginary): Add scale-to-zero labels

---

wordpress-all-in-one/Kraftfile

The current scale-to-zero cooldown (`1000ms`) in insufficient to fully start the Wordpress instance. With this, the first queries fail, as the service is not fully started. Simply put, the instance goes to sleep to soon after being started and, when it is woken up by a query, it cannot serve it.
Update the scale-to-zero cooldown to `3000ms`.

fix(examples): Increase scale-to-zero cooldown for Wordpress

---

node21-nextjs/README.md

Increase the memory allocated to the container running `node21-nextjs` example.
- `README.md` Change the memory allocated

fix(node21-nextjs): Increase the container memory allocation

---

mariadb/README.md

Update `README.md` to use `kraft cloud tunnel` for port forwarding, instead of `socat`.
Also add `--ssl=DISABLED` option. This disables SSL connections, which is enabled by default on some MySQL client configurations, causing a connection error:
```
ERROR 2206 (HY000): TLS/SSL error: SSL is required, but the server does
not support it
```

fix(mariadb): Use kraft cloud tunnel in README

---

.github/workflows/example-node-playwright-firefox-stable.yaml
.github/workflows/example-node-playwright-firefox-staging.yaml

For Playwright Firefox workflows, store screenshot output (from `curl`) in a file. Investigate the type of file (PNG).

fix(workflows): Store screenshot output in a file

---

.github/workflows/example-node-playwright-firefox-stable.yaml
.github/workflows/example-node-playwright-firefox-staging.yaml

Install `file` and `grep` packages in GitHub workflows for Playground Firefox.

fix(workflow): Install file and grep for Playground Firefox

---

.github/workflows/example-node21-websocket-stable.yaml
.github/workflows/example-node21-websocket-staging.yaml

Use `websocat` instead of `wscat` as the WebSocket client, as it can be used non-interactively.

fix(workflows): Use websocat instead of wscat

---

debian-ssh/.dockerignore
debian-ssh/.gitignore
debian-ssh/Dockerfile
debian-ssh/Kraftfile
debian-ssh/README.md
debian-ssh/sshd_config
debian-ssh/wrapper.sh

Introduce simple Debian SSH image. Use `kraft cloud tunnel` to create a tunnel to the instance and then use `ssh` to connect to the instance.

Introduce Debian SSH image

---

mariadb11.7-volumes/.dockerignore
mariadb11.7-volumes/.gitignore
mariadb11.7-volumes/50-server.cnf
mariadb11.7-volumes/Dockerfile
mariadb11.7-volumes/Kraftfile
mariadb11.7-volumes/README.md
mariadb11.7-volumes/wrapper.sh

Introduce a MariaDB install (11.7) that uses the `base-compat` runtime and volumes for persistence. A volume is mounted in `/var/lib` to store the database files in a persistent manner.
Add:
* `Dockerfile`: build the MariaDB filesystem
* `50-server.cnf`: MariaDB configuration
* `wrapper.sh`: wrapper start-up script for MariaDB
* `.dockerignore` / `.gitignore`: ignore generated files

feat(examples): Introduce MariaDB with volumes

---

postgres/README.md

Simplify docs. Use of socat as described does not work on macOS and is not needed.

docs(postgres): remove socat usage
