- http-rust1.75-actix-web4/Cargo.toml
- http-rust1.75-actix-web4/Dockerfile
- http-rust1.75-actix-web4/Kraftfile
- http-rust1.75-actix-web4/README.md
- http-rust1.75-actix-web4/src/main.rs
> feat(examples): Introduce Rust actix-web example

- http-rust1.75-rocket0.5/Cargo.toml
- http-rust1.75-rocket0.5/Dockerfile
- http-rust1.75-rocket0.5/Kraftfile
- http-rust1.75-rocket0.5/README.md
- http-rust1.75-rocket0.5/Rocket.toml
- http-rust1.75-rocket0.5/src/main.rs
> feat(examples): Introduce Rocket v0.5 with Rust example

- caddy/Kraftfile
- caddy/README.md
- caddy/rootfs/etc/caddy/Caddyfile
- caddy/rootfs/var/www/index.html
> feat(caddy): Introduce Caddy server example

- caddy/README.md
> feat(caddy): Update Caddy server example

- duckdb-go/Dockerfile
- duckdb-go/Kraftfile
- duckdb-go/README.md
- duckdb-go/src/go.mod
- duckdb-go/src/go.sum
- duckdb-go/src/main.go
> feat(duckdb-go): Add DuckDB Go SDK example

- nginx/Kraftfile
- nginx/README.md
- nginx/rootfs/conf/nginx.conf
- nginx/rootfs/wwwroot/index.html
- skipper/Kraftfile
- skipper/README.md
- skipper/example.eskip
- traefik/Kraftfile
- traefik/Kraftfile~
- traefik/README.md
- traefik/default.toml
- wazero-import-go/README.md
add nginx, skipper, traefik examples
> feat: add nginx, skipper, traefik example

- traefik/Kraftfile~
> feat (traefik): remove extraneous file

- nginx/Kraftfile
- nginx/README.md
Improve layout of `README.md` and `Kraftfile`.
> nginx: Improve file layout

- http-c/README.md
- http-cpp-boost/README.md
- http-cpp/README.md
- http-go1.21/README.md
- http-go1.21/server.go
- http-lua5.1/README.md
- http-node21/README.md
- http-perl5.38/README.md
- http-php8.2/README.md
- http-python3.12-django5.0/README.md
- http-python3.12-flask3.0/README.md
- http-python3.12/README.md
- http-ruby3.2/README.md
- http-rust1.73/README.md
- http-rust1.73/server.rs
- http-rust1.75-actix-web4/README.md
- http-rust1.75-actix-web4/src/main.rs
- http-rust1.75-rocket0.5/README.md
- http-rust1.75-rocket0.5/src/main.rs
- imaginary/README.md
- llama2/README.md
- node21-expressjs/README.md
- node21-nextjs/README.md
- python3.12-flask3.0-sqlite/README.md
- skipper/README.md
- spin-wagi-http/README.md
- spin-wagi-http/wagi-http-cpp/main.cpp
- wazero-import-go/README.md
> feat(examples): General standardization fixes

- node21-solid-start/Kraftfile
Reviewed-by: Felipe Huici <felipe@unikraft.io>
Approved-by: Felipe Huici <felipe@unikraft.io>
> feat(SolidStart): Use short-form runtime in KraftFile

- wordpress/Dockerfile
- wordpress/Kraftfile
- wordpress/README.md
Introduce Wordpress to be deployed on KraftCloud. It uses the `base-compat` image. It's used in conjunction with a MariaDB instance (the database) and an Nginx instance (the FastCGI proxy).
Add:
* `Dockerfile`: placeholder to extract the filesystem (Wordpress PHP FPM)
> feat(examples): Introduce Wordpress

- http-erlang26.2/.dockerignore
- http-erlang26.2/.gitignore
- http-erlang26.2/Dockerfile
- http-erlang26.2/Kraftfile
- http-erlang26.2/README.md
- http-erlang26.2/http_server.erl
- http-erlang26.2/wrapper.sh
> feat(examples): Add Erlang

- http-dotnet8.0/Dockerfile
- http-dotnet8.0/Kraftfile
Use proper build environment with cross-compilation.
> fix(dotnet): Fix macOS support

- http-go1.22-redis/Composefile
- http-go1.22-redis/Dockerfile
- http-go1.22-redis/Kraftfile
- http-go1.22-redis/README.md
- http-go1.22-redis/go.mod
- http-go1.22-redis/go.sum
- http-go1.22-redis/server.go
> feat(http-go1.22-redis): Introduce `compose.yaml` example with Go + Redis

- http-python3.12-django5.0/requirements.txt
- java17-springboot3.2.x/DemoApplication.java
- node18-prisma-rest-express/package.json
- node21-nextjs/package.json
- node21-remix/package-lock.json
- node21-solid-start/pnpm-lock.yaml
- ruby3.2-rails/app/controllers/hello_controller.rb
- wazero-import-go/age-calculator.go
Fix issue reported by dependabot: https://github.com/kraftcloud/examples/security
> Fix dependabot reported issues

- http-elixir1.16/Dockerfile
Add fix for macOS ARM-based builds
> fix(elixir): Add fix for macOS ARM-based builds

- opentelemetry-collector/Kraftfile
- opentelemetry-collector/README.md
Add 1GB (1024M) memory requirement for otel.
> fix(examples): Add memory requirement for otel

- wordpress-all-in-one/Dockerfile
- wordpress-all-in-one/Kraftfile
- wordpress-all-in-one/README.md
- wordpress-all-in-one/init.sql
- wordpress-all-in-one/rootfs/etc/nginx/fastcgi_params
- wordpress-all-in-one/rootfs/etc/nginx/nginx.conf
- wordpress-all-in-one/wrapper.sh
In this example, all components run in the same instance: Nginx, PHP FPM (Wordpress), MariaDB. It is meant to be run on the base-compat runtime.
> feat(examples): Add all-in-one Wordpress example

- grafana/Kraftfile
- http-elixir1.16/Kraftfile
- http-erlang26.2/Kraftfile
- http-java17/Kraftfile
- java17-spring-petclinic/Kraftfile
- java17-springboot3.2.x/Kraftfile
- node-express-puppeteer/Kraftfile
- opentelemetry-collector/Kraftfile
- ruby3.2-rails/Kraftfile
- wordpress/Kraftfile
Add stateful labels to heavy examples. This enables stateful scale-to-zero.
> feat(examples): Add stateful labels

- spin-wagi-http/goodbye-rust/Cargo.lock
Signed-off-by: Alexander Jung <alex@unikraft.cloud>
> chore(spin-wagi-http): Bump dependencies

- flask-redis/.dockerignore
- flask-redis/Dockerfile
- flask-redis/Kraftfile
- flask-redis/README.md
- flask-redis/app.py
- flask-redis/compose.yaml
- flask-redis/requirements.txt
Add and update [`flask-redis` app from the `awesome-compose` repository](https://github.com/docker/awesome-compose/tree/master/flask-redis).
There are two commits in the pull request:
1. The first commit copies the contents of the `flask-redis/` directory from the `awesome-compose` repository.
1. The second commit adds and updates contents to make it ready for Unikaft Cloud.
> feat(examples): Add `flask-redis` from `awesome-compose` repository

- .github/workflows/example-node-playwright-firefox-stable.yaml
- .github/workflows/example-node-playwright-firefox-staging.yaml
Fix indentation of curl command in `node-playwright-firefox` workflows.
> fix(workflows): Fix indent

- .github/workflows/example-node21-websocket-stable.yaml
- .github/workflows/example-node21-websocket-staging.yaml
Install `wscat` globally using `npm install -g wscat`, as instructed: https://www.npmjs.com/package/wscat
> fix(workflows): Install wscat in node21-websocket workflows
